import Head from 'next/head'
import Header from '../components/page/Header'
import Main from '../components/page/Main'
import Sidebar from '../components/page/Sidebar'
import Footer from '../components/page/Footer'
import { getAllFilesFrontMatter } from '../lib/mdx'

export default function Home({ posts }) {
  return (
    <div className="min-h-screen px-6 py-3 md:px-0">
      <Head>
        <title>AlexTorresDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex place-content-center">
        <div className="flex container">
          <Main posts={posts} />
          <Sidebar />
        </div>
      </div>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const posts = await getAllFilesFrontMatter()

  return {
    props: { posts }
  }
}
