name: Build & Deploy project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  avoid_redundant:
    name: ❌ Avoid redundant builds
    runs-on: ubuntu-22.04
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    name: 📦 Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create environment variables
        run: |
          echo "NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}" > .env
          echo "NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}" >> .env
      - name: Install, build, and upload artifact
        uses: withastro/action@v0

  deploy:
    name: 🚀 Deploy
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
